spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gcp:
      sql:
        instance-connection-name: wwartaservice:europe-central2:wwartaservice-db
        database-name: wwartaservice-db
      storage:
        bucket-name: ${GCS_BUCKET_NAME:wwartaservice-uploads}
        credentials:
          location: ${GOOGLE_APPLICATION_CREDENTIALS:}
      project-id: ${GCP_PROJECT_ID:wwartaservice}

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  mail:
    host: smtp.wp.pl
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          from: ${SPRING_MAIL_FROM:}

  task:
    scheduling:
      pool:
        size: 5

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}
  shutdown: graceful

app:
  upload:
    enabled: true
    local-path: ${UPLOAD_LOCAL_PATH:/tmp/uploads}
    gcs-enabled: ${GCS_UPLOAD_ENABLED:true}
